export const metadata = {
    title: 'Profile | My First next JS Project',
    description: 'Generated by create next app',
}

const ProfilePage = () => {
    return (
        <div>
            Profile Page
        </div>
    );
};

export default ProfilePage;