export const metadata = {
    title: 'Dashboard | My First next JS Project',
    description: 'Generated by create next app',
}
const DashboardPage = () => {
    return (
        <div>
            Dashboard
        </div>
    );
};

export default DashboardPage;